name: Release

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write
  
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v3.5.2"
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Patch manifest and zip
        run: |
          sed -i 's/v0.0.0/${{ steps.previoustag.outputs.tag }}/' custom_components/easgen/manifest.json
 
      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/ha_easgen"
          zip ha_easgen.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ github.workspace }}/custom_components/ha_easgen/ha_easgen.zip
