name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Release-Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          default-branch: main
          package-name: ha_easgen
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

      - uses: actions/checkout@v2
      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master
      - name: Patch manifest and zip
        run: |
          sed -i 's/v0.0.0/v0.1.3/' custom_components/easgen/manifest.json
        
          cd custom_components/easgen/
          zip ../../easgen.zip ./* 
      - uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./easgen.zip application/zip
