name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Release-Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          default-branch: main
          package-name: ha_easgen
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
  if_merged:
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.release }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - name: "Checkout the repository"
        uses: "actions/checkout@v3.5.2"
        with:
          fetch-depth: 0


      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Patch manifest and zip
        run: |
          yq -i -o json '.version="${{ steps.previoustag.outputs.tag }}"' \
            "${{ github.workspace }}/custom_components/ha_easgen/manifest.json"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/ha_easgen"
          zip ha_easgen.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: "${{ github.workspace }}/custom_components/ha_easgen/ha_easgen.zip"
          tag_name: "${{ steps.previoustag.outputs.tag }}"
