name: Release

on:
  workflow_run:
    workflows: [Validate]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  
jobs:
  release-please:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - 
        name: Release-Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          default-branch: main
          package-name: ha_easgen
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true