name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Release-Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          default-branch: main
          package-name: ha_easgen
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

      - name: "Checkout the repository"
        uses: "actions/checkout@v3.5.2"

      - name: Patch manifest and zip
        run: |
          sed -i 's/v0.0.0/${{ github.event.release.tag_name }}/' custom_components/easgen/manifest.json
 
      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/ha_easgen"
          zip ha_easgen.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ github.workspace }}/custom_components/ha_easgen/ha_easgen.zip
